### PR TITLE
Split the main() function to app.d

### PR DESCRIPTION
**Pull request by Manuzor**
... to allow for using the functionality as a library.

@WebFreak001 Does that look correct?

### CODE REVIEW

**Comment by WebFreak001** [comment]
quickly trying locally

**Comment by Manuzor** [comment]
I've also cleared out all unused packages in `app.d`. Compiles for me with both `-a x86` and `-a x86_64`.

**Comment by WebFreak001** [comment]
you also need to remove `targetType "executable"` from your dub.sdl

now that you have a app.d it will make an executable by default anyway.

Otherwise it seems like its working. Maybe a better API, but thats for the future. Works fine like it is right now

**Comment by WebFreak001** [comment]
I don't have an idl file but its compiling fine on linux without any errors, you might also want to add that to the readme

**Comment by Manuzor** [comment]
Yea, I also used an unconventional coding style for D. This tool was just a quick-and-dirty thing hacked together to make things work for me.

I'd be glad to accept pull requests! 😃

**Review by WebFreak001 — APPROVED** [review]
works fine as library on other projects now

**Comment by Manuzor** [comment]
@WebFreak001 Thanks for testing!

I've also added some notes to the README. If there's nothing else, I'll merge to `master`.

**Comment by WebFreak001** [comment]
PR when? Want to convert symbol names to phobos style

**Comment by Manuzor** [comment]
Done.

**Pull request merged**
